name: Rollout update on EC2 instance

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types: 
      - completed
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'requirements.txt'

jobs:

  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
        - uses: easingthemes/ssh-deploy@v5.0.0
          name: Deploy over SSH
          with:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            REMOTE_HOST: ${{ vars.SSH_HOST }}
            REMOTE_USER: ${{ vars.USER_NAME }}
            SCRIPT_AFTER: |
                ./script
                // PUT THE COMMANDS HERE

# jobs:
#   Deploy:
#     name: Deploy to EC2
#     runs-on: ubuntu-latest
    
#     steps:
#       - uses: actions/checkout@v2 
#       - name: Build & Deploy
#         env:
#             PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#             HOSTNAME: ${{secrets.SSH_HOST}}
#             USER_NAME: ${{secrets.USER_NAME}}
      
#         run: 
#           echo "$PRIVATE_KEY" > private_key.pem && chmod 600 private_key.pem
#           ssh -o StrictHostKeyChecking=no -i private_key.pem ${USER_NAME}@${HOSTNAME} '

#               sudo docker stop $(sudo docker ps -aq) &&
#               sudo docker rm $(sudo docker ps -aq) &&
#               cd py-lsp-server &&
#               cd python-lsp-server-docker && 
#               git pull origin main &&
#               sudo docker build -t python-lsp-server . &&
#               sudo docker run -p 8080:8080 python-lsp-server
#               '

