name: Rollout update on EC2 instance

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'requirements.txt'

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              # Now we have got the access of EC2 and we will start the deploy .
              sudo docker stop $(sudo docker ps -aq) &&
              cd py-lsp-server &&
              cd python-lsp-server-docker && 
              git pull origin main &&
              sudo docker build -t python-lsp-server . &&
              sudo docker run -p 8000:8000 python-lsp-server
              '