name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: SSH and run commands
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo docker stop $(sudo docker ps -aq)
          sudo docker rm $(sudo docker ps -aq)
          cd py-lsp-server/python-lsp-server-docker
          git pull origin main
          sudo docker build -t python-lsp-server .
          sudo docker run -p 8080:8080 -d python-lsp-server
