name: Rollout update on EC2 instance

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'requirements.txt'

jobs:

  Deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: easingthemes/ssh-deploy@v5.0.0
        name: Deploy over SSH
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ vars.SSH_HOST }}
          REMOTE_USER: ${{ vars.USER_NAME }}
          SCRIPT_AFTER: |
            sudo docker stop $(sudo docker ps -aq) 
            sudo docker rm $(sudo docker ps -aq) 
            cd py-lsp-server 
            cd python-lsp-server-docker 
            git pull origin main 
            sudo docker build -t python-lsp-server . 
            sudo docker run -p 8080:8080 python-lsp-server

