name: Build and Push Docker Image to ECR
on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'requirements.txt'
    paths-ignore:
      - 'demo-project/**'
      - 'readme.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        run: aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 339713082611.dkr.ecr.us-east-2.amazonaws.com

      - name: Build Docker image
        run: docker build -t bx-coding-lsp-server .

      - name: Tag Docker image
        run: docker tag bx-coding-lsp-server:latest 339713082611.dkr.ecr.us-east-2.amazonaws.com/bx-coding-lsp-server:latest

      - name: Push Docker image to ECR
        run: docker push 339713082611.dkr.ecr.us-east-2.amazonaws.com/bx-coding-lsp-server:latest